# ----- Begin vim-awesome -----
alias tmux="tmux -2"
# Ctrl s
alias vim="stty stop '' -ixoff ; vim"
ttyctl -f # 'Frozing' tty, so after any command terminal settings will be restored
fpath=(/usr/local/share/zsh-completions $fpath) # Activate zsh-completions
# ----- End vim-awesome -----
