# ----- Begin vim-awesome -----
alias tmux="tmux -2"
# Disable CTRL+S
alias vim="stty stop '' -ixoff ; vim"
ttyctl -f # 'Frozing' tty, so after any command terminal settings will be restored
# ----- End vim-awesome -----
